# Generated by Django 6.0.4 on 2026-05-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webUXUI_1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyectos',
            old_name='datos_importantes',
            new_name='Datos_importantes',
        ),
        migrations.RenameField(
            model_name='proyectos',
            old_name='creación',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='proyectos',
            old_name='usuario',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='proyectos',
            name='descripción',
        ),
        migrations.AddField(
            model_name='proyectos',
            name='Descripción',
            field=models.TextField(blank=True),
        ),
    ]
