# Generated by Django 6.0.4 on 2026-05-20 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webUXUI_1', '0002_rename_datos_importantes_proyectos_datos_importantes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectos',
            name='datecompleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
