# Generated by Django 6.0.4 on 2026-05-23 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webUXUI_1', '0003_proyectos_datecompleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyectos',
            old_name='Datos_importantes',
            new_name='Importante',
        ),
    ]
