# Generated by Django 6.0.4 on 2026-06-08 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webUXUI_1', '0004_rename_datos_importantes_proyectos_importante'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyectos',
            old_name='title',
            new_name='Título',
        ),
    ]
